INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','C.IVOIRE','ساحل العاج','ABJ','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','ALGERIE','الجزائر','ALG','الجزائر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','HOLLANDE','هولندا','AMS','هولندا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','TURQUIE','تركيا','AYT','تركيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ESPAGNE','إسبانيا','BCN','إسبانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','SERBIE','صربيا','BEG','صربيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','LIBYE','ليبيا','BEN','ليبيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ALLEMAGNE','ألمانيا','BER','ألمانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','BES','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','MALI','مالي','BKO','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','BLQ','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','BOD','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','BELGIQUE','بلجيكا','BRU','بلجيكا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','SLOVAQUIE','سلوفاكيا','BTS','سلوفاكيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','HONGRIE','المجر','BUD','المجر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ROUMANIE','رومانيا','BUH','رومانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','EGYPTE','مصر','CAI','مصر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','MAROC','المغرب','CAS','المغرب');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','CDG','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','CIA','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','GUINEE','غينيا','CKY','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','MAROC','المغرب','CMN','المغرب');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','ALGERIE','الجزائر','CZL','الجزائر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','DJE','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','SENEGAL','السنغال','DKR','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','CAMEROUN','الكاميرون','DLA','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','A.SEOUDITE','العربية السعودية','DMM','العربية السعودية');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','QATAR','قطر','DOH','قطر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','SENEGAL','السنغال','DSS','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ALLEMAGNE','ألمانيا','DUS','ألمانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','FCO','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ALLEMAGNE','ألمانيا','FRA','ألمانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','GAE','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','GAF','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','CAMEROUN','الكاميرون','GOU','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','SUISSE','سويسرا ','GVA','سويسرا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ALLEMAGNE','ألمانيا','HAM','ألمانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','TURQUIE','تركيا','IST','تركيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','A.SEOUDITE','العربية السعودية','JED','العربية السعودية');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','POLOGNE','بولندا','KRK','بولندا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','LBG','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','R.UNI','بريطانيا','LGW','بريطانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','R.UNI','بريطانيا','LHR','بريطانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','SLOVENIE','سلوفينيا','LJU','سلوفينيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','R.UNI','بريطانيا','LON','بريطانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','LYS','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ESPAGNE','إسبانيا','MAD','إسبانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','A.SEOUDITE','العربية السعودية','MED','العربية السعودية');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','MIL','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','MIR','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','LIBYE','ليبيا','MJI','ليبيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','MALTE','مالطا','MLA','مالطا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','MRS','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ALLEMAGNE','ألمانيا','MUC','ألمانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','MXP','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','NCE','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','NIGER','النيجر','NIM','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','Tchad','تشاد','NJM','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','MAURITANIE','موريطانيا','NKC','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','NTE','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','Portugal','البرتغال','OPO','البرتغال');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','ALGERIE','الجزائر','ORN','الجزائر');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','ORY','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ROUMANIE','رومانيا','OTP','رومانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('Afrique subsaharienne','أفريقيا جنوب الصحراء','BURKINA FASO','بوركينا فاسو','OUA','أفريقيا جنوب الصحراء');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','PAR','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','R.TCHEQUE','الجمهورية التشيكية','PRG','الجمهورية التشيكية');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','ROM','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('MOYEN ORIENT ','الشرق الأوسط','A.SEOUDITE','العربية السعودية','RUH','العربية السعودية');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','SFA','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','R.UNI','بريطانيا','STN','بريطانيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','SXB','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','TBJ','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','FRANCE','فرنسا ','TLS','فرنسا ');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','TOE','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('NORD AFRIQUE','افريقيا الشمالية','TUNISIE','تونس','TUN','تونس');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','ITALIE','إيطاليا','VCE','إيطاليا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','AUTRICHE','النمسا','VIE','النمسا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','POLOGNE','بولندا','WAW','بولندا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('AMERIQUE DU NORD','أمريكا الشمالية','CANADA','كندا','YUL','كندا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','CROATIE','كرواتيا','ZAG','كرواتيا');
INSERT INTO Market (zonegeo,zonegeoarabe,pays,paysArabe,escale_D,PaysArRapport) VALUES ('EUROPE','أوروبا','SUISSE','سويسرا ','ZRH','سويسرا ');